timeout: 1200s
substitutions:
  _REGION: us-central1
  _CLUSTER:  yougo-projects-labs-gke
steps:
  - name: gcr.io/cloud-builders/kubectl
    id: Configure kubectl
    args:
      - cluster-info
    env:
      - CLOUDSDK_COMPUTE_REGION=$_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER
      - KUBECONFIG=/workspace/.kube/config
      
  - name: gcr.io/yougo-projects-labs/helm
    id: Deploy chart
    args: ['upgrade', '--install', 'airflow apache-airflow/airflow   --set dags.persistence.enabled=true   --set dags.gitSync.enabled=true', '--namespace', 'airflow']
    env:
      - HELM_EXPERIMENTAL_OCI=1
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=true
